// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: business_service.proto

package business_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("business_service.proto", fileDescriptor_bcbff8ebd207b3bd) }

var fileDescriptor_bcbff8ebd207b3bd = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2a, 0x2d, 0xce,
	0xcc, 0x4b, 0x2d, 0x2e, 0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x89, 0x4b, 0xf1, 0xc1, 0x58, 0x10, 0x19, 0xa3, 0x66, 0x66, 0x2e,
	0x7e, 0x27, 0xa8, 0x50, 0x30, 0x44, 0x8f, 0x90, 0x0b, 0x17, 0x9f, 0x73, 0x51, 0x6a, 0x62, 0x49,
	0x2a, 0x4c, 0x42, 0x48, 0x5e, 0x0f, 0xae, 0x0d, 0x55, 0x26, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8,
	0x44, 0x8a, 0x1f, 0xa1, 0xc0, 0x35, 0xb7, 0xa0, 0xa4, 0x52, 0x89, 0x41, 0xc8, 0x91, 0x8b, 0xdb,
	0x3d, 0xb5, 0x04, 0x6e, 0x84, 0x0c, 0x42, 0x05, 0x92, 0x30, 0x4c, 0xbf, 0x10, 0x42, 0x16, 0x26,
	0xa5, 0xc4, 0x20, 0x14, 0xcd, 0x25, 0xe0, 0x9e, 0x5a, 0xe2, 0x98, 0x93, 0x03, 0x13, 0x4b, 0x2d,
	0x16, 0x52, 0x44, 0x31, 0x07, 0x45, 0x0e, 0x66, 0x98, 0x12, 0x3e, 0x25, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x4a, 0x0c, 0x20, 0x5f, 0x86, 0x16, 0xa4, 0xe0, 0xf0, 0x25, 0xaa, 0x0c, 0x1e, 0x5f,
	0xba, 0x70, 0xf1, 0xb9, 0xa4, 0xe6, 0xa4, 0x62, 0x37, 0x05, 0x55, 0x06, 0xb7, 0x29, 0x4e, 0xda,
	0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x8c, 0xc7, 0x72,
	0x0c, 0x51, 0x92, 0xe9, 0xa9, 0x79, 0xe0, 0x18, 0xd2, 0x47, 0x8f, 0xd2, 0x24, 0x36, 0xb0, 0xb8,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x3d, 0x9c, 0xea, 0xed, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BusinessServiceClient is the client API for BusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessServiceClient interface {
	CreateBusiness(ctx context.Context, in *CreateBusinessRequest, opts ...grpc.CallOption) (*Empty, error)
	GetBusiness(ctx context.Context, in *GetBusinessRequest, opts ...grpc.CallOption) (*Business, error)
	GetAllBusinesses(ctx context.Context, in *GetAllBusinessesRequest, opts ...grpc.CallOption) (*GetAllBusinessesResponse, error)
	UpdateBusiness(ctx context.Context, in *UpdateBusinessRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteBusiness(ctx context.Context, in *DeleteBusinessRequest, opts ...grpc.CallOption) (*Empty, error)
}

type businessServiceClient struct {
	cc *grpc.ClientConn
}

func NewBusinessServiceClient(cc *grpc.ClientConn) BusinessServiceClient {
	return &businessServiceClient{cc}
}

func (c *businessServiceClient) CreateBusiness(ctx context.Context, in *CreateBusinessRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/business.BusinessService/CreateBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetBusiness(ctx context.Context, in *GetBusinessRequest, opts ...grpc.CallOption) (*Business, error) {
	out := new(Business)
	err := c.cc.Invoke(ctx, "/business.BusinessService/GetBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetAllBusinesses(ctx context.Context, in *GetAllBusinessesRequest, opts ...grpc.CallOption) (*GetAllBusinessesResponse, error) {
	out := new(GetAllBusinessesResponse)
	err := c.cc.Invoke(ctx, "/business.BusinessService/GetAllBusinesses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) UpdateBusiness(ctx context.Context, in *UpdateBusinessRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/business.BusinessService/UpdateBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) DeleteBusiness(ctx context.Context, in *DeleteBusinessRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/business.BusinessService/DeleteBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServiceServer is the server API for BusinessService service.
type BusinessServiceServer interface {
	CreateBusiness(context.Context, *CreateBusinessRequest) (*Empty, error)
	GetBusiness(context.Context, *GetBusinessRequest) (*Business, error)
	GetAllBusinesses(context.Context, *GetAllBusinessesRequest) (*GetAllBusinessesResponse, error)
	UpdateBusiness(context.Context, *UpdateBusinessRequest) (*Empty, error)
	DeleteBusiness(context.Context, *DeleteBusinessRequest) (*Empty, error)
}

// UnimplementedBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessServiceServer struct {
}

func (*UnimplementedBusinessServiceServer) CreateBusiness(ctx context.Context, req *CreateBusinessRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) GetBusiness(ctx context.Context, req *GetBusinessRequest) (*Business, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) GetAllBusinesses(ctx context.Context, req *GetAllBusinessesRequest) (*GetAllBusinessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBusinesses not implemented")
}
func (*UnimplementedBusinessServiceServer) UpdateBusiness(ctx context.Context, req *UpdateBusinessRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) DeleteBusiness(ctx context.Context, req *DeleteBusinessRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBusiness not implemented")
}

func RegisterBusinessServiceServer(s *grpc.Server, srv BusinessServiceServer) {
	s.RegisterService(&_BusinessService_serviceDesc, srv)
}

func _BusinessService_CreateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).CreateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/CreateBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).CreateBusiness(ctx, req.(*CreateBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/GetBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetBusiness(ctx, req.(*GetBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetAllBusinesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBusinessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetAllBusinesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/GetAllBusinesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetAllBusinesses(ctx, req.(*GetAllBusinessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_UpdateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).UpdateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/UpdateBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).UpdateBusiness(ctx, req.(*UpdateBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_DeleteBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).DeleteBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/DeleteBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).DeleteBusiness(ctx, req.(*DeleteBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "business.BusinessService",
	HandlerType: (*BusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBusiness",
			Handler:    _BusinessService_CreateBusiness_Handler,
		},
		{
			MethodName: "GetBusiness",
			Handler:    _BusinessService_GetBusiness_Handler,
		},
		{
			MethodName: "GetAllBusinesses",
			Handler:    _BusinessService_GetAllBusinesses_Handler,
		},
		{
			MethodName: "UpdateBusiness",
			Handler:    _BusinessService_UpdateBusiness_Handler,
		},
		{
			MethodName: "DeleteBusiness",
			Handler:    _BusinessService_DeleteBusiness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business_service.proto",
}
