// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auth_service.proto

package auth_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("auth_service.proto", fileDescriptor_0f39bb026ca10b68) }

var fileDescriptor_0f39bb026ca10b68 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcd, 0x6a, 0xdb, 0x40,
	0x14, 0x85, 0x65, 0xb7, 0x94, 0x72, 0x45, 0x8d, 0x3c, 0xc5, 0x6d, 0x71, 0x5b, 0x51, 0xb4, 0xe9,
	0xce, 0x05, 0xdb, 0x5d, 0x14, 0x77, 0x61, 0xfc, 0x83, 0x31, 0xfd, 0xa1, 0xb8, 0xf5, 0xa6, 0x9b,
	0xa2, 0xc6, 0x97, 0x44, 0x20, 0x5b, 0x8a, 0x66, 0x9c, 0xa0, 0x37, 0xc9, 0xd3, 0x64, 0x9d, 0x65,
	0x9e, 0x20, 0x18, 0xe7, 0x45, 0xc2, 0x68, 0x3c, 0x9a, 0xd1, 0x58, 0x22, 0x1b, 0x83, 0xbf, 0x7b,
	0xce, 0x91, 0x74, 0x2e, 0x33, 0x40, 0xfc, 0x2d, 0x3b, 0xfb, 0x47, 0x31, 0xb9, 0x08, 0x4e, 0xb0,
	0x13, 0x27, 0x11, 0x8b, 0xc8, 0x53, 0xce, 0xda, 0xc0, 0x7f, 0x05, 0xe9, 0xee, 0xea, 0x60, 0x2f,
	0x29, 0x26, 0xbf, 0x85, 0x8e, 0xf4, 0x00, 0xc6, 0x09, 0xfa, 0x0c, 0x39, 0x24, 0xaf, 0x3b, 0x99,
	0x54, 0x91, 0x05, 0x9e, 0x6f, 0x91, 0xb2, 0x36, 0x88, 0x01, 0x47, 0x9e, 0x45, 0x3e, 0x83, 0x3d,
	0x43, 0xc6, 0xff, 0x8c, 0xd2, 0xf9, 0x84, 0xbc, 0x11, 0x43, 0x0d, 0x95, 0xdb, 0x06, 0xd0, 0xc8,
	0x35, 0xd3, 0xb5, 0x1f, 0x84, 0xe4, 0xad, 0xe1, 0xcc, 0x68, 0xb9, 0xf9, 0x2b, 0x34, 0x96, 0xf1,
	0xca, 0x67, 0xf8, 0xcb, 0xa7, 0xf4, 0x32, 0x4a, 0x56, 0xd2, 0x5c, 0xa4, 0xd2, 0x6c, 0x8b, 0xe1,
	0x74, 0x1d, 0xb3, 0xd4, 0xb3, 0x48, 0x1f, 0x40, 0xe8, 0xf4, 0xcf, 0x54, 0xa4, 0xda, 0x35, 0xc1,
	0x10, 0x8b, 0x2e, 0x45, 0xca, 0x5d, 0xdd, 0xbb, 0x3a, 0xd8, 0x8b, 0x28, 0x44, 0x59, 0x71, 0x5f,
	0x56, 0xcc, 0x61, 0xb1, 0x62, 0x4e, 0x2a, 0x9e, 0x2d, 0x3a, 0xe6, 0x02, 0xa3, 0x63, 0x89, 0x8c,
	0x9a, 0x38, 0xf6, 0x2c, 0xf2, 0x05, 0x5e, 0xe4, 0x9a, 0x9f, 0xfe, 0x1a, 0x49, 0xdb, 0x30, 0x72,
	0x58, 0x6e, 0x1d, 0xc0, 0xf3, 0x83, 0x8a, 0x92, 0x56, 0xc1, 0x45, 0xa5, 0xe1, 0x95, 0x32, 0x7c,
	0x0f, 0x28, 0x5b, 0x20, 0x8d, 0xa3, 0x0d, 0x45, 0xbd, 0x60, 0xfd, 0x23, 0x15, 0x79, 0xac, 0x60,
	0xdd, 0xa5, 0x48, 0x45, 0xc1, 0xd7, 0x4f, 0xa0, 0x39, 0x0e, 0x03, 0xdc, 0xb0, 0x3f, 0x69, 0x9c,
	0xd7, 0x3c, 0x04, 0x47, 0x94, 0xaa, 0x46, 0xe4, 0xbd, 0x5e, 0xb6, 0xe2, 0x15, 0x6f, 0x33, 0x83,
	0xe6, 0x0c, 0x99, 0x92, 0x8d, 0xd2, 0xf9, 0x8a, 0xb8, 0x79, 0x13, 0xc5, 0x81, 0xcc, 0x70, 0x0e,
	0x8f, 0xc8, 0x87, 0x9e, 0x45, 0xbe, 0xc1, 0x4b, 0x43, 0x9f, 0xad, 0xe2, 0x43, 0x69, 0x94, 0xbe,
	0x90, 0xb2, 0xb0, 0x1f, 0xd9, 0xa9, 0x51, 0x88, 0x6a, 0xa7, 0x46, 0xa3, 0x32, 0xe2, 0x9d, 0x19,
	0x61, 0x2c, 0x6a, 0x08, 0x8e, 0x58, 0xcb, 0x71, 0x4d, 0x26, 0xaf, 0xa8, 0x69, 0x08, 0x8e, 0x58,
	0xd1, 0x71, 0x82, 0xc9, 0xcb, 0x13, 0x46, 0x1f, 0x6f, 0xf6, 0x6e, 0xed, 0x76, 0xef, 0xd6, 0x76,
	0x7b, 0xb7, 0x76, 0x75, 0xef, 0x5a, 0x7f, 0x5b, 0xa7, 0xb8, 0xc9, 0x2e, 0xa8, 0x4f, 0xfa, 0x2d,
	0xf6, 0xff, 0x59, 0xc6, 0x7a, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x82, 0x73, 0x5b, 0xdc,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*User, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*User, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.UserService/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.UserService/GetUserByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.UserService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUserByID(context.Context, *GetUserByIDRequest) (*User, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*User, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*Empty, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*Empty, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*Empty, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByID(ctx context.Context, req *GetUserByIDRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByEmail(ctx context.Context, req *GetUserByEmailRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (*UnimplementedUserServiceServer) UpdatePassword(ctx context.Context, req *UpdatePasswordRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.UserService/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByID(ctx, req.(*GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.UserService/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.UserService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _UserService_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserService_GetUserByEmail_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _UserService_UpdatePassword_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoleServiceClient interface {
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*Empty, error)
	GetRoleByID(ctx context.Context, in *GetRoleByIDRequest, opts ...grpc.CallOption) (*Role, error)
	GetRoleByName(ctx context.Context, in *GetRoleByNameRequest, opts ...grpc.CallOption) (*Role, error)
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*RoleListResponse, error)
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*Empty, error)
}

type roleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoleServiceClient(cc *grpc.ClientConn) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.RoleService/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRoleByID(ctx context.Context, in *GetRoleByIDRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/auth.RoleService/GetRoleByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRoleByName(ctx context.Context, in *GetRoleByNameRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/auth.RoleService/GetRoleByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*RoleListResponse, error) {
	out := new(RoleListResponse)
	err := c.cc.Invoke(ctx, "/auth.RoleService/GetRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.RoleService/UpdateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.RoleService/DeleteRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
type RoleServiceServer interface {
	CreateRole(context.Context, *CreateRoleRequest) (*Empty, error)
	GetRoleByID(context.Context, *GetRoleByIDRequest) (*Role, error)
	GetRoleByName(context.Context, *GetRoleByNameRequest) (*Role, error)
	GetRoles(context.Context, *GetRolesRequest) (*RoleListResponse, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*Empty, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*Empty, error)
}

// UnimplementedRoleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoleServiceServer struct {
}

func (*UnimplementedRoleServiceServer) CreateRole(ctx context.Context, req *CreateRoleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (*UnimplementedRoleServiceServer) GetRoleByID(ctx context.Context, req *GetRoleByIDRequest) (*Role, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleByID not implemented")
}
func (*UnimplementedRoleServiceServer) GetRoleByName(ctx context.Context, req *GetRoleByNameRequest) (*Role, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleByName not implemented")
}
func (*UnimplementedRoleServiceServer) GetRoles(ctx context.Context, req *GetRolesRequest) (*RoleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoles not implemented")
}
func (*UnimplementedRoleServiceServer) UpdateRole(ctx context.Context, req *UpdateRoleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (*UnimplementedRoleServiceServer) DeleteRole(ctx context.Context, req *DeleteRoleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}

func RegisterRoleServiceServer(s *grpc.Server, srv RoleServiceServer) {
	s.RegisterService(&_RoleService_serviceDesc, srv)
}

func _RoleService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.RoleService/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRoleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRoleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.RoleService/GetRoleByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRoleByID(ctx, req.(*GetRoleByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRoleByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRoleByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.RoleService/GetRoleByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRoleByName(ctx, req.(*GetRoleByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.RoleService/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.RoleService/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpdateRole(ctx, req.(*UpdateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.RoleService/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _RoleService_CreateRole_Handler,
		},
		{
			MethodName: "GetRoleByID",
			Handler:    _RoleService_GetRoleByID_Handler,
		},
		{
			MethodName: "GetRoleByName",
			Handler:    _RoleService_GetRoleByName_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _RoleService_GetRoles_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _RoleService_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _RoleService_DeleteRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}

// ClientTypeServiceClient is the client API for ClientTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientTypeServiceClient interface {
	CreateClientType(ctx context.Context, in *CreateClientTypeRequest, opts ...grpc.CallOption) (*Empty, error)
	GetClientTypeById(ctx context.Context, in *GetClientTypeByIdRequest, opts ...grpc.CallOption) (*ClientType, error)
	GetClientTypeByName(ctx context.Context, in *GetClientTypeByNameRequest, opts ...grpc.CallOption) (*ClientType, error)
	GetClientTypes(ctx context.Context, in *GetClientTypesRequest, opts ...grpc.CallOption) (*ClientTypeListResponse, error)
	UpdateClientType(ctx context.Context, in *UpdateClientTypeRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteClientType(ctx context.Context, in *DeleteClientTypeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type clientTypeServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientTypeServiceClient(cc *grpc.ClientConn) ClientTypeServiceClient {
	return &clientTypeServiceClient{cc}
}

func (c *clientTypeServiceClient) CreateClientType(ctx context.Context, in *CreateClientTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.ClientTypeService/CreateClientType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientTypeServiceClient) GetClientTypeById(ctx context.Context, in *GetClientTypeByIdRequest, opts ...grpc.CallOption) (*ClientType, error) {
	out := new(ClientType)
	err := c.cc.Invoke(ctx, "/auth.ClientTypeService/GetClientTypeById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientTypeServiceClient) GetClientTypeByName(ctx context.Context, in *GetClientTypeByNameRequest, opts ...grpc.CallOption) (*ClientType, error) {
	out := new(ClientType)
	err := c.cc.Invoke(ctx, "/auth.ClientTypeService/GetClientTypeByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientTypeServiceClient) GetClientTypes(ctx context.Context, in *GetClientTypesRequest, opts ...grpc.CallOption) (*ClientTypeListResponse, error) {
	out := new(ClientTypeListResponse)
	err := c.cc.Invoke(ctx, "/auth.ClientTypeService/GetClientTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientTypeServiceClient) UpdateClientType(ctx context.Context, in *UpdateClientTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.ClientTypeService/UpdateClientType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientTypeServiceClient) DeleteClientType(ctx context.Context, in *DeleteClientTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.ClientTypeService/DeleteClientType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientTypeServiceServer is the server API for ClientTypeService service.
type ClientTypeServiceServer interface {
	CreateClientType(context.Context, *CreateClientTypeRequest) (*Empty, error)
	GetClientTypeById(context.Context, *GetClientTypeByIdRequest) (*ClientType, error)
	GetClientTypeByName(context.Context, *GetClientTypeByNameRequest) (*ClientType, error)
	GetClientTypes(context.Context, *GetClientTypesRequest) (*ClientTypeListResponse, error)
	UpdateClientType(context.Context, *UpdateClientTypeRequest) (*Empty, error)
	DeleteClientType(context.Context, *DeleteClientTypeRequest) (*Empty, error)
}

// UnimplementedClientTypeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientTypeServiceServer struct {
}

func (*UnimplementedClientTypeServiceServer) CreateClientType(ctx context.Context, req *CreateClientTypeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClientType not implemented")
}
func (*UnimplementedClientTypeServiceServer) GetClientTypeById(ctx context.Context, req *GetClientTypeByIdRequest) (*ClientType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientTypeById not implemented")
}
func (*UnimplementedClientTypeServiceServer) GetClientTypeByName(ctx context.Context, req *GetClientTypeByNameRequest) (*ClientType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientTypeByName not implemented")
}
func (*UnimplementedClientTypeServiceServer) GetClientTypes(ctx context.Context, req *GetClientTypesRequest) (*ClientTypeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientTypes not implemented")
}
func (*UnimplementedClientTypeServiceServer) UpdateClientType(ctx context.Context, req *UpdateClientTypeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClientType not implemented")
}
func (*UnimplementedClientTypeServiceServer) DeleteClientType(ctx context.Context, req *DeleteClientTypeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClientType not implemented")
}

func RegisterClientTypeServiceServer(s *grpc.Server, srv ClientTypeServiceServer) {
	s.RegisterService(&_ClientTypeService_serviceDesc, srv)
}

func _ClientTypeService_CreateClientType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientTypeServiceServer).CreateClientType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ClientTypeService/CreateClientType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientTypeServiceServer).CreateClientType(ctx, req.(*CreateClientTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientTypeService_GetClientTypeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientTypeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientTypeServiceServer).GetClientTypeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ClientTypeService/GetClientTypeById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientTypeServiceServer).GetClientTypeById(ctx, req.(*GetClientTypeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientTypeService_GetClientTypeByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientTypeByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientTypeServiceServer).GetClientTypeByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ClientTypeService/GetClientTypeByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientTypeServiceServer).GetClientTypeByName(ctx, req.(*GetClientTypeByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientTypeService_GetClientTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientTypeServiceServer).GetClientTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ClientTypeService/GetClientTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientTypeServiceServer).GetClientTypes(ctx, req.(*GetClientTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientTypeService_UpdateClientType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientTypeServiceServer).UpdateClientType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ClientTypeService/UpdateClientType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientTypeServiceServer).UpdateClientType(ctx, req.(*UpdateClientTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientTypeService_DeleteClientType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientTypeServiceServer).DeleteClientType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ClientTypeService/DeleteClientType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientTypeServiceServer).DeleteClientType(ctx, req.(*DeleteClientTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientTypeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.ClientTypeService",
	HandlerType: (*ClientTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClientType",
			Handler:    _ClientTypeService_CreateClientType_Handler,
		},
		{
			MethodName: "GetClientTypeById",
			Handler:    _ClientTypeService_GetClientTypeById_Handler,
		},
		{
			MethodName: "GetClientTypeByName",
			Handler:    _ClientTypeService_GetClientTypeByName_Handler,
		},
		{
			MethodName: "GetClientTypes",
			Handler:    _ClientTypeService_GetClientTypes_Handler,
		},
		{
			MethodName: "UpdateClientType",
			Handler:    _ClientTypeService_UpdateClientType_Handler,
		},
		{
			MethodName: "DeleteClientType",
			Handler:    _ClientTypeService_DeleteClientType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}
